### ISSUE TITLE
Redirect Feature and Sheer UI

### ISSUE THREAD

**Issue by SiriusBits** [sitecorerick/constellation-sitecore9#1]
Curious on whether the Redirects feature will get deprecated or replaced in Sitecore 9.1+. The use cases outlined seem pretty solid and the implementation as well. But with the Sheer UI interface, it seems a replacement for that would be a necessity. 

Overall, Constellation looks pretty good. Nice work!

**Comment by sitecorerick** [comment]
The Redirects feature  (as deployed) will continue to work as long as Sitecore supports the Desktop, which they've said will always be SheerUI. - It works fine in 9.1.1 and I imagine it will work in 9.2 as well.

the "guts" of the redirect feature are UX independent, relying on stock Sitecore data functionality. If Sitecore decided to deprecate SheerUI, then I would seriously consider rewriting the front-end of Redirects as traditional ASP.NET MVC, making it more of a console app. The only reason it remains a SheerUI app is for continuity between Sitecore editors.
