### ISSUE TITLE
Redirect Manager Layout not found exception

### ISSUE THREAD

**Issue by retohugi** [sitecorerick/constellation-sitecore9#2]
I've deployed the Redirects Feature 9.1.2.16479 to a Sitecore 9.1.0 instance. All files deployed, going to the desktop and starting the Redirects Manager i receive a layout not found error message. Looking at the layout details of core:/sitecore/content/Applications/Redirect Manager 
the therein referenced layout is not part of the item package and thus missing after package installation. 
```
<?xml version="1.0" encoding="utf-16"?>
<r xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" 
l="{2E4C69E9-4C35-492F-8974-E3CFB59B83C1}" /></r>
```

So, my best guess at the moment is, that I'd need an updated item package to make the module work. Is it hidden within another "base" module of constellation? 

thanks for looking into this.
BR, reto

**Comment by sitecorerick** [comment]
Hi, sorry for the late response. No, the Redirects feature is pretty self-contained.

I will look into the issue. Thanks for your patience.

**Comment by sitecorerick** [comment]
Ok, I have found the missing layout and settings. I will be updating the NuGet package in the next few hours. Thanks again for your patience.

**Comment by sitecorerick** [comment]
Install the latest version of the NuGet package to fix your issue:
`Install-Package Constellation.Feature.Redirects -Version 9.1.6.19219`
Thanks again for taking the time to report this error. Sorry for the delay.
